name: Deploy CloudFormation Template

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: AKIAW3MEBHZPRAZBQLVL
        aws-secret-access-key: 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
        aws-region: ap-south-1

    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation deploy \
          --template-file title/template.yaml
          --stack-name your-stack-name \
          aws configure set default.region ap-south-1

