name: Deploy CloudFormation Template

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: "AKIAW3MEBHZPRAZBQLVL"
        AWS_SECRET_ACCESS_KEY: "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"
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region us-east-1

    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation deploy \
          --template-file .github/workflows/main.yml \
          --stack-name aws \
    
